version: '3'

services:
  postgres:
    build: 
      context: ./backend/db/
      dockerfile: prod-local.Dockerfile

  backend:
    build: 
      context: ./backend
      dockerfile: prod-local.Dockerfile
    depends_on:
      - postgres
    links: 
      - postgres
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: always
    
  frontend:
      context: ./frontend
      dockerfile: prod-local.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./uploads:/etc/nginx/html/uploads
    depends_on:
      - backend