version: '3'
services:
  postgres:
    build: 
      context: ./backend/db/
      dockerfile: dev.Dockerfile

  backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    ports: 
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
    links: 
      - postgres
    restart: always
    volumes:
      - ./upload:/usr/src/app/upload
      - ./backend:/usr/src/app/
      - /usr/src/app/node_modules
    
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: dev.Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./upload:/usr/src/app/public/upload
  #     - ./frontend:/usr/src/app/
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - backend